config:
  service: |
    [SERVICE]
        Daemon Off
        Flush 1
        Log_Level info
        Parsers_File /fluent-bit/etc/parsers.conf
        Parsers_File /fluent-bit/etc/conf/custom_parsers.conf
        HTTP_Server On
        HTTP_Listen 0.0.0.0
        HTTP_Port 2020
        Health_Check On

  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Exclude_Path /var/log/containers/*_istio-proxy*,/var/log/containers/*_istio-init*
        multiline.parser docker, cri
        Tag app.*
        Mem_Buf_Limit 100MB
        Skip_Long_Lines On
        Read_from_Head On

  filters: |
    [FILTER]
        Name kubernetes
        Match app.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name grep
        Match *
        Regex $kubernetes['labels']['fluentbit-logs'] true

  outputs: |
    [OUTPUT]
        Name cloudwatch_logs
        Match app.*
        region ${region}
        log_group_name /aws/containerinsights/${cluster_name}/application
        log_stream_prefix app.
        auto_create_group true
        extra_user_agent container-insights
        workers 1

  customParsers: |
    [PARSER]
        Name docker
        Format json
        Time_Key time
        Time_Format %Y-%m-%dT%H:%M:%S %z
        Time_Keep On
