pilot:
  podLabels:
    fluentbit-logs: 'true'
  autoscaleEnabled: false
  traceSampling: 100
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
global:
  logAsJson: true
  proxy:
    excludeInboundPorts: "5432"
    excludeOutboundPorts: "5432"
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
meshConfig:
  accessLogFile: /dev/stdout
