pilot:
  podLabels:
    fluentbit-logs: 'true'
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 3
  cpu:
    targetAverageUtilization: 85
  memory:
    targetAverageUtilization: 85
  traceSampling: 100
  resources:
    requests:
      cpu: 500m
      memory: 1024Mi
    limits:
      cpu: 768m
      memory: 1500Mi
  image: marlapativ/pilot:1.22.3
global:
  defaultPodDisruptionBudget:
    enabled: true
  logAsJson: true
  proxy:
    holdApplicationUntilProxyStarts: true
    excludeInboundPorts: '5432'
    excludeOutboundPorts: '5432'
    resources:
      requests:
        cpu: 10m
        memory: 40Mi
      limits:
        cpu: 100m
        memory: 100Mi
meshConfig:
  accessLogFile: /dev/stdout
